### ISSUE TITLE
Single quote in alias field causes UI for TV not to load.

### ISSUE THREAD

**Issue by neoneddy** [webinmd/mixedimage#5]
While single quotes should not be in an alias field, it's causing  some issues.

**Comment by webinmd** [comment]
> While single quotes should not be in an alias field, it's causing some issues.

Give an example please
In modx quotes are cut from alias

**Comment by neoneddy** [comment]
Not sure if you still need the example.  Here is a page with and without the single quote
![image](https://user-images.githubusercontent.com/819083/49595324-53db4380-f93d-11e8-88b7-80c0110d6581.png)

![image](https://user-images.githubusercontent.com/819083/49595604-f3003b00-f93d-11e8-9ce8-0169a56e3279.png)
