### ISSUE TITLE
Ошибка в имени файла при загрузке

### ISSUE THREAD

**Issue by alexsoin** [webinmd/mixedimage#7]
При загрузке файла с именем типа: "название файла.jpg", "название_файла.jpg", "название.файла.jpg", "название-файла.jpg" и "название-файла.JPG" неверно подставляются имена файлов в тв поле, так как все эти варианты по итогу при загрузке меняются на "nazvanie-fajla.jpg"

**Comment by webinmd** [comment]
не используется ли компонент filetranslit? 
Попробуйте включить в системных настройках встроенную в компонент транслитерацию mixedimage.translit

**Comment by alexsoin** [comment]
filetranslit не установлен, из подобных дополнений установлен только компонент translit

**Comment by alexsoin** [comment]
включение системной настройки **mixedimage.translit** помогло. Спасибо
