### ISSUE TITLE
Problems with MIGX

### ISSUE THREAD

**Issue by jenswittmann** [webinmd/mixedimage#8]
Hello,
thanks for the nice plugin. Its works great and the drag'n drop is great. But if i used it in MIGX it crashed. I use MODX 2.7.1. Here is the console log:

``
Uncaught TypeError: b[(d.xtype || e)] is not a constructor
    at Object.create (ext-all.js:21)
    at MODx.load (modx.js?v=f64f0b59:85)
    at eval (eval at <anonymous> (ext-all.js:21), <anonymous>:3:31)
    at eval (<anonymous>)
    at HTMLSpanElement.<anonymous> (ext-all.js:21)
    at B (ext-base.js:21)
    at F (ext-base.js:21)
``

Cheers
Jens

**Comment by webinmd** [comment]
Hello,
this happens when using drag'n drop in MIGX? 
Show pls your configuration

**Comment by jenswittmann** [comment]
Hello,
when i use mixedimage inside MIGXdb i get a blank field. So i think there is a problem loading the assets for mixedimage inside MIGXdb that caused a rendering problem.

Do you know if it was working inside MIGX?

**Comment by webinmd** [comment]
I use the component inside migxDB as a separate TV field
![image](https://user-images.githubusercontent.com/966234/64028849-12826800-cb4c-11e9-8549-7d99e1612ea6.png)

And it works

![image](https://user-images.githubusercontent.com/966234/64028726-d8b16180-cb4b-11e9-8c8f-05063d7d4bbd.png)


**migx_img is simple TV field type mixedimage**

**Comment by jenswittmann** [comment]
Same be my. I use it inside a MIGX CMP. Maybe there is a problem?

**Comment by webinmd** [comment]
Confirm this bug.
Is in MIGX CMP
